# Generated by Django 3.1.2 on 2020-10-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='age',
            field=models.CharField(default='0', max_length=20, verbose_name='Возраст'),
        ),
    ]
