# Generated by Django 3.1.2 on 2020-10-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20201020_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='choice2',
            field=models.CharField(default='1', max_length=2, verbose_name='Choice2'),
        ),
        migrations.AddField(
            model_name='information',
            name='choice3',
            field=models.CharField(default='1', max_length=2, verbose_name='Choice3'),
        ),
        migrations.AddField(
            model_name='information',
            name='choice4',
            field=models.CharField(default='1', max_length=2, verbose_name='Choice4'),
        ),
        migrations.AddField(
            model_name='information',
            name='choice5',
            field=models.CharField(default='1', max_length=2, verbose_name='Choice5'),
        ),
        migrations.AlterField(
            model_name='information',
            name='pref2',
            field=models.CharField(default='1', max_length=100, verbose_name='Preference_menu'),
        ),
    ]
