# Generated by Django 3.1.2 on 2020-10-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='sсope',
            new_name='scope',
        ),
    ]
